server.port: 8080
service.contextPath: '/product-api/v1/products'

spring.application.name: product

logging:
  level:
    com.myRetail.product: INFO

product:
  keyspaceName: myRetail_price
  api:
    errorcode:
      API_ERR_NOT_FOUND: API_ERR_NOT_FOUND
      API_ERR_INVALID_PRICE: API_ERR_INVALID_PRICE
      API_ERR_INVALID_PRODUCTID: API_ERR_INVALID_PRODUCTID
    errormessage:
      API_ERR_NOT_FOUND: Sorry, requested product is not found
      API_ERR_INVALID_PRICE: Please enter a valid price
      API_ERR_INVALID_PRODUCTID: Please enter a valid productId
  rest:
    getProductsUrl: https://redsky-uat.perf.target.com/redsky_aggregations/v1/redsky/case_study_v1?key={key}&tcin={tcin}
    headerName: token
    totalconnections: 10
    connectiontimeout: 3000
    readtimeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,env,beans
    jmx:
      exposure:
        include: health
